### ISSUE TITLE
nuget package compiled with public token=null

### ISSUE THREAD

**Issue by rugunda** [tkellogg/Trappings#1]
Hi I have a issue with the nuget package being compiled against mongo c# assembly with publictoken=null

I cannot use assembly redirect to use a new version. 

How can I get around this issue.

**Comment by tkellogg** [comment]
This is the worst headache in .NET, I'm so sorry you have to deal with it. This problem will continue to be a pain in our collective asses as long as the mongo driver is strongly named. I recommend building the code yourself, to match your correct mongo version. You can do a git clone or just download the source as a zip (git clone has a clear upgrade path thought) and drop in the desired mongo driver version (or update nuget) and build! Sorry this is such a pain...

**Comment by rugunda** [comment]
Thanks, . I have a workaround using  custome assembly loading [AppDomain.CurrentDomain.AssemblyResolve+=]  which works okay for now.  

PS: I am enjoying using Trappings

**Comment by tkellogg** [comment]
I'm glad that you find it useful. It's not particularly full-featured, but it does a nice job cleaning up tests. If you have any suggestions, feel free to contribute!
